// 测试公共数据：深度优先扁平任务树（模拟后端 schedule_tasks 结构）
// task_type: 阶段任务(phase) / 普通任务(normal) / 节点任务(node)

// 用于折叠联动测试（computeVisibleTasks）+ 甘特图集成渲染
export const buildTree = [
  {
    id: 1,
    parent_id: null,
    task_type: "阶段任务",
    depth: 0,
    name: "阶段A",
    planned_start: "2026-07-01",
    planned_end: "2026-07-20",
    duration_days: 20,
    bg_color: "#8B5CF6",
    completion_status: "进行中",
  },
  {
    id: 2,
    parent_id: 1,
    task_type: "普通任务",
    depth: 1,
    name: "子任务A1",
    planned_start: "2026-07-02",
    planned_end: "2026-07-10",
    duration_days: 9,
    bg_color: null,
    completion_status: "进行中",
  },
  {
    id: 3,
    parent_id: 2,
    task_type: "普通任务",
    depth: 2,
    name: "孙任务A1a",
    planned_start: "2026-07-03",
    planned_end: "2026-07-08",
    duration_days: 6,
    bg_color: null,
    completion_status: "进行中",
  },
  {
    id: 4,
    parent_id: 1,
    task_type: "普通任务",
    depth: 1,
    name: "子任务A2",
    planned_start: "2026-07-11",
    planned_end: "2026-07-20",
    duration_days: 10,
    bg_color: "#10B981",
    completion_status: "未开始",
  },
  {
    id: 5,
    parent_id: null,
    task_type: "阶段任务",
    depth: 0,
    name: "阶段B",
    planned_start: "2026-07-05",
    planned_end: "2026-07-25",
    duration_days: 21,
    bg_color: null,
    completion_status: "进行中",
  },
  {
    id: 6,
    parent_id: 5,
    task_type: "普通任务",
    depth: 1,
    name: "子任务B1",
    planned_start: "2026-07-05",
    planned_end: "2026-07-25",
    duration_days: 21,
    bg_color: null,
    completion_status: "已完成",
  },
];

// 用于颜色继承测试（修复②）
export const colorTree = [
  {
    id: 1,
    parent_id: null,
    task_type: "阶段任务",
    name: "P",
    planned_start: "2026-07-01",
    planned_end: "2026-07-30",
    duration_days: 30,
    bg_color: "#PARENT",
    completion_status: "进行中",
  },
  {
    id: 2,
    parent_id: 1,
    task_type: "普通任务",
    name: "C-no-bg",
    planned_start: "2026-07-01",
    planned_end: "2026-07-10",
    duration_days: 10,
    bg_color: null,
    completion_status: "进行中",
  },
  {
    id: 3,
    parent_id: 2,
    task_type: "普通任务",
    name: "G-no-bg",
    planned_start: "2026-07-01",
    planned_end: "2026-07-05",
    duration_days: 5,
    bg_color: null,
    completion_status: "进行中",
  },
  {
    id: 4,
    parent_id: null,
    task_type: "普通任务",
    name: "D-own-bg",
    planned_start: "2026-07-01",
    planned_end: "2026-07-05",
    duration_days: 5,
    bg_color: "#OWN",
    completion_status: "进行中",
  },
  {
    id: 5,
    parent_id: null,
    task_type: "普通任务",
    name: "E-status",
    planned_start: "2026-06-01",
    planned_end: "2026-06-10",
    duration_days: 10,
    bg_color: null,
    completion_status: "已完成",
  },
  {
    id: 6,
    parent_id: 1,
    task_type: "普通任务",
    name: "C2-own-bg",
    planned_start: "2026-07-01",
    planned_end: "2026-07-05",
    duration_days: 5,
    bg_color: "#CHILD",
    completion_status: "进行中",
  },
];
